### PR TITLE
correct the typo

### PR DESCRIPTION
**Pull request by faraazahmad**

### CODE REVIEW

**Comment by faraazahmad** [comment]
`I signed It!`

**Comment by adamcrume** [comment]
It still says that you haven't signed the CLA.  Can you double-check at https://cla.developers.google.com/clas?

**Comment by faraazahmad** [comment]
do i have to provide my github linked email or the gmail one?

**Comment by adamcrume** [comment]
You have to provide the email address in the commit (faraaz98@live.com).

**Comment by adamcrume** [comment]
Are you able to fix the CLA issue?  If not, I'd like to close this request to clean out the queue.

**Comment by adamcrume** [comment]
I'm closing this pull request since it's not making any progress.  If you fix the CLA issue, feel free to open a new one.

**Pull request closed without merging**
