### PR TITLE
migrate from random crate to rand

### PR DESCRIPTION
**Pull request by RealAdarsh**
Migrate from random crate to rand #378

### CODE REVIEW

**Comment by adamcrume** [comment]
Can you fix the test failures?  The `./test-all` script should succeed.

**Comment by RealAdarsh** [comment]
Hello Adam, I am new to open-source, Could you please help me how to fix this? I could try fixing it.

**Comment by adamcrume** [comment]
All the other places in the file that reference the `random` crate also need to be switched to the `rand` crate, and `Cargo.toml` needs to be updated.  This isn't a simple find-and-replace, because the types and functions in the two crates aren't identical.

**Comment by adamcrume** [comment]
This was fixed in https://github.com/tensorflow/rust/pull/384.

**Pull request closed without merging**
