### PR TITLE
A few tweaks to allow building on Windows

### PR DESCRIPTION
**Pull request by Tomcc**
I wanted to get this to work on Windows because it's my preferred dev environment.

Building Tensorflow from source on Windows is not supported and extremely difficult, but fortunately it's still possible to steal the binaries from the official `pip` installation and link them with this wrapper (with enough magic).

This PR lets you define a `TF_RUST_PREBUILT_DIR` env variable that points to a folder containing `tensorflow.dll` and `tensorflow.lib` that will be used by `build.rs` to link. This could possibly be useful on other platforms as well if you don't want to `install` the binaries you built yourself.

I've also changed `buffer.rs` to require Nightly (but only on Windows) in order to replace `posix_memalign`. 

From my tests with the examples, everything seems to work alright. I don't mind if you prefer not to integrate this, but I thought it could be useful to someone else!
It's not particularly clean but it makes setting up on Windows at least possible.

### CODE REVIEW

**Comment by Tomcc** [comment]
I didn't realize there was a CLA... I work for another BigCorp and it's a significant effort to even figure out if I can grant the rights the CLA requires. I guess... I'll maybe be back in a few weeks :P

**Comment by sanmai-NL** [comment]
@Tomcc: checked it out yet? I would be a pity if your contribution gets lost because of this.

**Comment by Tomcc** [comment]
Yep... As I expected, it's a grey area.

**Comment by Tomcc** [comment]
Woops. Clicked the wrong button :)
I've asked and didn't get any clear answer. Let me know if it's better that I delete this so someone else can come up with a similar solution.

**Comment by adamcrume** [comment]
If it's going to take a while to get approval, I'd suggest closing the pull request and reopening it if/when you get approval, just so the list of pending pull requests isn't cluttered.  It'd be great if BigCorp lets you sign the CLA, because I don't have a Windows setup, so help with getting it to work on Windows would be much appreciated.

**Comment by adamcrume** [comment]
Is this obsolete due to #114?  If not, are you able to sign the CLA?  If this is obsolete or you won't be able to sign the CLA, I'd like to close this request to clean out the queue.

**Comment by Tomcc** [comment]
Yeah nevermind, sorry but it's too much work. Closing this one.

**Pull request closed without merging**
