### PR TITLE
Modify tensorflow-sys/src/lib.rs to be bindgen generated

### PR DESCRIPTION
**Pull request by nbigaouette-eai**
This MR gets rid of the hand-written `tensorflow-sys/src/lib.rs` file, and replaces it with two files:
1. `tensorflow-sys/src/bindgen.rs` is the result of `bindgen --blacklist-type max_align_t /usr/include/tensorflow/c_api.h > tensorflow-sys/src/bindgen.rs`;
2. `tensorflow-sys/src/lib.rs` simply `include!()` the generated wrapper, adding some `#![allow(...)]` and re-exporting the enum values.

I've added the option `--blacklist-type max_align_t` to bindgen so that the automatically generated unit tests don't fail:
```
     Running `/home/nbigaouette/projects/agents/tensorflow_rust.git/target/debug/deps/tensorflow_sys-b18d6c19e08d67bd`

running 5 tests
test bindgen_test_layout_TF_AttrMetadata ... ok
test bindgen_test_layout_TF_Buffer ... ok
test bindgen_test_layout_TF_Output ... ok
test bindgen_test_layout_TF_Input ... ok
test bindgen_test_layout_max_align_t ... FAILED

failures:

---- bindgen_test_layout_max_align_t stdout ----
        thread 'bindgen_test_layout_max_align_t' panicked at 'assertion failed: `(left == right)` (left: `24`, right: `32`): Size of: max_align_t', src/bindgen.rs:82
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    bindgen_test_layout_max_align_t

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```

See https://github.com/servo/rust-bindgen/issues/550 for the bindgen issue about this unit test.

Should close issue #57.

### CODE REVIEW

**Comment by nbigaouette-eai** [comment]
I signed it!

**Comment by nbigaouette** [comment]
The CI failure is due to tensorflow failing to build and _not_ this MR.

See similar issues in the main tensorflow repository:
* https://github.com/tensorflow/tensorflow/issues/6678
* https://github.com/tensorflow/tensorflow/issues/6572

MR https://github.com/tensorflow/rust/pull/65 could aleviate this problem by using a pre-built binary for tensoflow. This would help a lot!

**Comment by adamcrume** [comment]
Could you add a script for running bindgen?

**Comment by adamcrume** [comment]
Thanks!

**Comment by daschl** [comment]
I think this is a great middle ground between hand-generating the API and forcing couple of compile time dependencies on the user :)

**Pull request merged**
