### PR TITLE
FIXES THE #290

### PR DESCRIPTION
**Pull request by AnakinSkywalkeer**
I added the new enum called AttrValue  and after that i fill the empty field default_value and allowed_values in OpArgDef.

FIXES the #290

### CODE REVIEW

**Comment by AnakinSkywalkeer** [comment]
hi @adamcrume i made this pull request can u check it if i need to change smth

**Comment by adamcrume** [comment]
Please ensure that `./test-all` passes.  It looks like the change needs to be formatted.

**Comment by AnakinSkywalkeer** [comment]
@adamcrume hey sorry was busy, so i can u tell what i can use in place  of super::tensor::TensorProtPaeo in Tensor() 
```
#[derive(Debug, Clone, PartialEq)]
pub enum AttrValue {
    S(::std::vec::Vec<u8>),
    I(i64),
    F(f32),
    B(bool),
    FieldType(DataType),
    Shape(Shape),
    Tensor(super::tensor::TensorProtPaeo),
    List(AttrValue_ListValue),
    Func(NameAttrList),
    Placeholder(::std::string::String),
}
```

**Comment by AnakinSkywalkeer** [comment]
it passed the ./test-all

**Pull request closed without merging**
