### PR TITLE
Add support for static linking

### PR DESCRIPTION
**Pull request by sgrif**
While tensorflow doesn't officially support building a static library,
it is relatively straightforward on Unix using instructions found by the
community at https://github.com/tensorflow/tensorflow/issues/28388. This
allows tensorflow-sys to use a static library should one already exist.

No attempt is made to add any support for automatically building a
static library. It is entirely on the user to go through the trouble of
producing `libtensorflow.a` should they want to use it. This commit
*only* allows the user to ask the build script to use the static library
they have built.

### CODE REVIEW

**Comment by adamcrume** [comment]
Can you make sure the checks all pass?

**Comment by sgrif** [comment]
Whoops, looks like I forgot to run `cargo fmt`. I will make sure to run it first thing Monday morning. The PR should otherwise be fine to review in the meantime

**Comment by sgrif** [comment]
The checks should pass now but I'm unable to rerun them

**Review by adamcrume — CHANGES_REQUESTED** [review]
Can you run `./test-all` while building statically?  When I tried, it crashed with: `Non-OK-status: status status: NOT_FOUND: Op type not registered 'NoOp'`.

**Comment by sgrif** [comment]
I left the job where this was desirable and no longer have the machine I was using to work on this. So someone else will have to pick this up to make this happen.

Sorry for wasting your time

**Comment by adamcrume** [comment]
I'm sorry to hear that, and I'm sorry I didn't review this earlier.  I hope your job situation is okay!

**Pull request closed without merging**
